#include "sperl_op_info.h"
#include "sperl_parser.h"






SPerl_uchar* const SPerl_OP_INFO_C_CODE_NAMES[] = {
  "NULL",
  "DOUBLE2FLOAT",
  "DOUBLE2IINT",
  "DDOUBLE2LONG",
  "FLOAT2DDOUBLE",
  "FLOAT2INT",
  "FLOAT2LONG",
  "INT2CHAR",
  "INT2UCHAR",
  "INT2DOUBLE",
  "INT2FLOAT",
  "INT2LONG",
  "INT2SHORT",
  "LONG2DOUBLE",
  "LONG2FLOAT",
  "LONG2INT",
  "ADD_INT",
  "ADD_LONG",
  "ADD_FLOAT",
  "ADD_DOUBLE",
  "SUBTRACT_INT",
  "SUBTRACT_LONG",
  "SUBTRACT_FLOAT",
  "SUBTRACT_DOUBLE",
  "MULTIPLY_INT",
  "MULTIPLY_LONG",
  "MULTIPLY_FLOAT",
  "MULTIPLY_DOUBLE",
  "DIVIDE_INT",
  "DIVIDE_LONG",
  "DIVIDE_FLOAT",
  "DIVIDE_DOUBLE",
  "NEGATE_INT",
  "LNEGATE_LONG",
  "NEGATE_FLOAT",
  "NEGATE_DOUBLE",
  "REMAINDER_INT",
  "REMAINDER_LONG",
  "REMAINDER_FLOAT",
  "REMAINDER_DOUBLE",
  "IPLUS",
  "LPLUS",
  "FPLUS",
  "DPLUS",
  "RETURN_INT",
  "RETURN_LONG",
  "FETURN_FLOAT",
  "RETURN_DOUBLE",
  "RETURN_REF",
  "RETURN",
  "IAND",
  "LAND",
  "IOR",
  "LOR",
  "IXOR",
  "LXOR",
  "POP",
  "POP2",
};


SPerl_OP_INFO* SPerl_OP_INFO_new(SPerl_PARSER* parser) {
  return SPerl_PARSER_alloc_memory_pool(parser, sizeof(SPerl_OP_INFO));
}
