#ifndef SPVM_DATA_HEADER_H
#define SPVM_DATA_HEADER_H

enum {
  SPVM_DATA_HEADER_C_TYPE_OBJECT,
  SPVM_DATA_HEADER_C_TYPE_STRING,
  SPVM_DATA_HEADER_C_TYPE_ARRAY_NUMERIC,
  SPVM_DATA_HEADER_C_TYPE_ARRAY_STRING,
};

#endif
