#ifndef SPVM_DATA_H
#define SPVM_DATA_H

struct SPVM_ref {
  int8_t type;
  int8_t sub_type;
  int16_t byte_size;
  int32_t ref_count;
};

enum {
  SPVM_REF_C_TYPE_OBJECT,
  SPVM_REF_C_TYPE_STRING,
  SPVM_REF_C_TYPE_ARRAY,
};

enum {
  SPVM_REF_C_SUB_TYPE_NULL,
  SPVM_REF_C_SUB_TYPE_ARRAY_REF,
  SPVM_REF_C_SUB_TYPE_ARRAY_BYTE,
  SPVM_REF_C_SUB_TYPE_ARRAY_SHORT,
  SPVM_REF_C_SUB_TYPE_ARRAY_INT,
  SPVM_REF_C_SUB_TYPE_ARRAY_LONG,
  SPVM_REF_C_SUB_TYPE_ARRAY_FLOAT,
  SPVM_REF_C_SUB_TYPE_ARRAY_DOUBLE,
};

#endif
